### ISSUE TITLE
fonction : getAllDateInfoFromDate : doc disponible dans le package mais pas exporté 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresHDF5#13]
fonction disponible dans la documentation (pas d'exemple) mais pas exportée dans le fichier NAMESPACE 

oubli ? erreur ? à exporter ? exemple à rajouter ? 

pour l'instant j'ai une erreur lors de l'appel 

```R 
> getAllDateInfoFromDate(myDataHdf5)
Error in getAllDateInfoFromDate(myDataHdf5) : 
  could not find function "getAllDateInfoFromDate"

```

**Comment by TitouanRobert** [comment]
add @noRd

**Comment by jalazawa** [comment]
même chose pour getTime 

> getTime(myData, "annual")
Error in getTime(myData, "annual") : could not find function "getTime"

**Comment by TitouanRobert** [comment]
Fait

**Comment by jalazawa** [comment]
ok
