### ISSUE TITLE
R CMD build bug --> rhdf5

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresHDF5#3]
wrong version ? 

available version 2.20 !

http://bioconductor.org/packages/release/bioc/html/rhdf5.html

```R
==> Rcmd.exe INSTALL --no-multiarch --with-keep.source antaresHDF5

* installing to library 'D:/Users/jalazawa/Documents/R/win-library/3.3'
* installing *source* package 'antaresHdf5' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'rhdf5' 2.18.0 is being loaded, but >= 2.21.2 is required
ERROR: lazy loading failed for package 'antaresHdf5'
* removing 'D:/Users/jalazawa/Documents/R/win-library/3.3/antaresHdf5'

Exited with status 1.


```

**Comment by bthieurmel** [comment]
Needed actual dev version....

source('https://bioconductor.org/biocLite.R')
BiocInstaller::useDevel() # for latest version
biocLite('rhdf5')

And perhaps latest R....

2017-10-03 14:10 GMT+02:00 Jalal Edine Zawam <notifications@github.com>:

**Comment by jalazawa** [comment]
oki, can we add this information to the readme ? add perhaps delete this information when 2.21 is released

**Comment by jalazawa** [comment]
useDevel is not enough

![compil](https://user-images.githubusercontent.com/22026724/31125427-8da773f0-a848-11e7-8f1d-022d513127fb.png)


I will try to update R...

**Comment by jalazawa** [comment]
Ok when I update R to 3.4 

![compil_2png](https://user-images.githubusercontent.com/22026724/31127339-e9aed552-a84e-11e7-9ae6-b89ad784a67a.png)


edit the file description ? and readme ? 

Depends: R (>= 3.4.0)

**Comment by bthieurmel** [comment]
Yes. Done.
