### ISSUE TITLE
install rhdf5 on Travis and on appVeyor

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresHDF5#4]
building / testing is KO on Travis because rhdf5 is not installed. 

Can we found a solution ? 

![install_rhdf5_rte-antares-rpackage_antareshdf5_travis ci](https://user-images.githubusercontent.com/22026724/31128184-4c64c858-a851-11e7-9cc5-6497b8d6304a.png)

on appVeyor is also ko. 

package 'rhdf5' successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\appveyor\AppData\Local\Temp\1\Rtmp6LoFPp\d

and after we try to install rhdf5 from CRAN 

Rscript -e 'options(repos=c(CRAN="https://cran.rstudio.com")); remotes::install_deps(dependencies = TRUE, type="both")'
Skipping 1 packages not available: rhdf5

**Comment by jalazawa** [comment]
edit travis.yml ? 

site 

http://jtleek.com/protocols/travis_bioc_devel/


install:
  ## For a CRAN package
  - ./travis-tool.sh install_r <package>
  
  ## For a Bioconductor package
  - ./travis-tool.sh install_bioc <package>
  
  ## For a GitHub package
  - ./travis-tool.sh install_github <package>

**Comment by jalazawa** [comment]
finally : 

I think we must use r_github_packages and bioc_packages :

https://docs.travis-ci.com/user/languages/r/

and 

https://github.com/rte-antares-rpackage/antaresProcessing/blob/master/.travis.yml

**Comment by TitouanRobert** [comment]
For travis : 
r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - rte-antares-rpackage/antaresRead@develop
 - rte-antares-rpackage/antaresProcessing

For appVeyor : 

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc zlibbioc
  - travis-tool.sh install_bioc rhdf5
  - ./travis-tool.sh install_github rte-antares-rpackage/antaresRead@develop
  - ./travis-tool.sh install_github rte-antares-rpackage/antaresProcessing

**Comment by jalazawa** [comment]
ok
